

trigger:
- main

pool:
  Infra-agent-pool

variables:
  spn: work-load-federation-service-connection

steps:
- task: TerraformInstaller@1
  displayName: 'terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(spn)
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmStorageAccountName: 'stgbknd'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstat'

- task: TerraformTask@5
  displayName: 'terraform fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: $(spn)

- task: TerraformTask@5
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: $(spn)